spring.application.name=alertflow-hub

server.port=8083

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5430/postgres
spring.datasource.username=alert
spring.datasource.password=root

# <---- Swagger ----> http://localhost:8083/swagger-ui/index.html


jwt.token.lifetime=18000000
jwt.token.signature=KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
